#!/bin/bash

# Assign the arguments to variables
function="$1"
input_file_path="$2"
config_file_path="$3"

# Run the gradle command with the arguments
gradle app:run -q --args "$function $input_file_path $config_file_path"