/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package printscript.v1.app

import com.github.ajalt.clikt.core.subcommands
import printscript.v1.cli.Format
import printscript.v1.cli.Lint
import printscript.v1.cli.PrintScript
import printscript.v1.cli.Run
import java.util.*

fun main(args: Array<String>) =
    PrintScript().subcommands(Run(), Lint(), Format()).main(args)
